# Generated by Django 2.2.9 on 2020-01-28 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='check date')),
                ('maintain', models.CharField(choices=[('O', 'Oil Change'), ('G', 'Gas Tank Full'), ('A', 'Available for Sale')], default='O', max_length=1)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Car')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
